using Microsoft.EntityFrameworkCore;
using ArcBackend.Models;

namespace ArcBackend.Data
{
    public class ArcDbContext : DbContext
    {
        public ArcDbContext(DbContextOptions<ArcDbContext> options) : base(options) { }

        public DbSet<User> Users => Set<User>();
        public DbSet<Product> Products => Set<Product>();
        public DbSet<Sailor> Sailors => Set<Sailor>();
        public DbSet<Vendor> Vendors => Set<Vendor>();
        public DbSet<StockEntry> StockEntries => Set<StockEntry>();
        public DbSet<SalesOrder> SalesOrders => Set<SalesOrder>();
        public DbSet<SalesOrderItem> SalesOrderItems => Set<SalesOrderItem>();
        public DbSet<CardTransaction> CardTransactions => Set<CardTransaction>();
        public DbSet<SystemSetting> SystemSettings => Set<SystemSetting>();
        public DbSet<CategoryMaster> Categories => Set<CategoryMaster>();
        public DbSet<SubCategoryMaster> SubCategories => Set<SubCategoryMaster>();
        public DbSet<BrandMaster> Brands => Set<BrandMaster>();
        public DbSet<ShipUnitMaster> ShipsUnits => Set<ShipUnitMaster>();
        public DbSet<RankMaster> Ranks => Set<RankMaster>();

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure decimal precision
            foreach (var property in modelBuilder.Model.GetEntityTypes()
                .SelectMany(t => t.GetProperties())
                .Where(p => p.ClrType == typeof(decimal) || p.ClrType == typeof(decimal?)))
            {
                property.SetColumnType("numeric(18,2)");
            }

            modelBuilder.Entity<SalesOrder>()
                .HasMany(o => o.Items)
                .WithOne()
                .HasForeignKey(i => i.BillNo)
                .OnDelete(DeleteBehavior.Cascade);

            modelBuilder.Entity<CategoryMaster>()
                .HasMany(c => c.SubCategories)
                .WithOne()
                .HasForeignKey(s => s.CategoryId)
                .OnDelete(DeleteBehavior.Cascade);
        }

        public void SeedInitialData()
        {
            Database.EnsureCreated();

            try
            {
                Database.ExecuteSqlRaw(@"
                    CREATE TABLE IF NOT EXISTS ""Categories"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""Code"" text NOT NULL,
                        ""Name"" text NOT NULL,
                        ""Description"" text NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS ""SubCategories"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""CategoryId"" integer NOT NULL REFERENCES ""Categories""(""Id"") ON DELETE CASCADE,
                        ""CategoryName"" text NOT NULL,
                        ""Name"" text NOT NULL,
                        ""Description"" text NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS ""Brands"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""Name"" text NOT NULL,
                        ""CategoryName"" text NOT NULL,
                        ""Description"" text NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS ""ShipsUnits"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""Name"" text NOT NULL,
                        ""Command"" text NOT NULL,
                        ""Status"" text NOT NULL
                    );
                    CREATE TABLE IF NOT EXISTS ""Ranks"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""Name"" text NOT NULL,
                        ""Category"" text NOT NULL
                    );
                ");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Table creation check: {ex.Message}");
            }

            if (!Users.Any())
            {
                Users.AddRange(
                    new User { Id = "U-001", Username = "superadmin", Role = "Super Admin", Email = "superadmin@arc.navy.in", Status = "Active", LastLogin = "13/07/2026 19:23:41" },
                    new User { Id = "U-002", Username = "baradmin", Role = "Bar Admin", Email = "baradmin@arc.navy.in", Status = "Active", LastLogin = "13/07/2026 19:23:41" },
                    new User { Id = "U-003", Username = "posuser1", Role = "POS User", Email = "pos1@arc.navy.in", Status = "Active", LastLogin = "13/07/2026 18:48:52" },
                    new User { Id = "U-004", Username = "posuser2", Role = "POS User", Email = "pos2@arc.navy.in", Status = "Active", LastLogin = "12/07/2026 20:10:11" },
                    new User { Id = "U-005", Username = "stockmgr", Role = "Stock Manager", Email = "stock@arc.navy.in", Status = "Active", LastLogin = "11/07/2026 09:30:00" },
                    new User { Id = "U-006", Username = "reporter", Role = "Report Viewer", Email = "report@arc.navy.in", Status = "Inactive", LastLogin = "05/07/2026 14:22:30" }
                );
            }

            if (!Products.Any())
            {
                Products.AddRange(
                    new Product { Code = "0000000002", Name = "ROYAL STAG 750 ML", Category = "LIQUOR", Sub = "WHISKY", Price = 720.00m, Stock = 45, AlertQty = 10 },
                    new Product { Code = "0000000003", Name = "MCDOWELL NO 1 750 ML", Category = "LIQUOR", Sub = "WHISKY", Price = 680.00m, Stock = 32, AlertQty = 10 },
                    new Product { Code = "0000000004", Name = "OLD MONK RUM 750 ML", Category = "LIQUOR", Sub = "RUM", Price = 550.00m, Stock = 60, AlertQty = 15 },
                    new Product { Code = "0000000005", Name = "BACARDI WHITE RUM 750", Category = "LIQUOR", Sub = "RUM", Price = 850.00m, Stock = 20, AlertQty = 5 },
                    new Product { Code = "0000000006", Name = "SMIRNOFF VODKA 750 ML", Category = "LIQUOR", Sub = "VODKA", Price = 920.00m, Stock = 18, AlertQty = 5 },
                    new Product { Code = "0000000007", Name = "KINGFISHER PREMIUM BEER 650", Category = "LIQUOR", Sub = "BEER", Price = 180.00m, Stock = 120, AlertQty = 25 },
                    new Product { Code = "0000000008", Name = "CARLSBERG ELEPHANT 650 ML", Category = "LIQUOR", Sub = "BEER", Price = 210.00m, Stock = 85, AlertQty = 20 },
                    new Product { Code = "0000000009", Name = "COCA COLA 2L", Category = "SOFT DRINKS", Sub = "COLD DRINK", Price = 90.00m, Stock = 50, AlertQty = 10 },
                    new Product { Code = "0000000010", Name = "PEPSI 2L", Category = "SOFT DRINKS", Sub = "COLD DRINK", Price = 90.00m, Stock = 40, AlertQty = 10 },
                    new Product { Code = "0000000011", Name = "SPRITE 2L", Category = "SOFT DRINKS", Sub = "COLD DRINK", Price = 90.00m, Stock = 35, AlertQty = 10 },
                    new Product { Code = "0000000012", Name = "RED BULL 250 ML", Category = "SOFT DRINKS", Sub = "COLD DRINK", Price = 125.00m, Stock = 65, AlertQty = 15 },
                    new Product { Code = "0000000013", Name = "CHICKEN BIRYANI", Category = "FOOD", Sub = "NON VEGETARIAN", Price = 180.00m, Stock = 25, AlertQty = 5 },
                    new Product { Code = "0000000014", Name = "PANEER BUTTER MASALA", Category = "FOOD", Sub = "VEGETARIAN", Price = 140.00m, Stock = 30, AlertQty = 5 },
                    new Product { Code = "0000000015", Name = "BUTTER NAAN", Category = "FOOD", Sub = "BREAD/ROTI", Price = 35.00m, Stock = 100, AlertQty = 20 },
                    new Product { Code = "0000000016", Name = "PARTY CHICKEN PLATTER", Category = "PARTY", Sub = "PARTY NONVEG", Price = 650.00m, Stock = 10, AlertQty = 2 },
                    new Product { Code = "0000000017", Name = "PARTY VEG PLATTER", Category = "PARTY FOOD", Sub = "PARTY VEG", Price = 480.00m, Stock = 12, AlertQty = 2 }
                );
            }

            if (!Sailors.Any())
            {
                Sailors.AddRange(
                    new Sailor { Id = "0001777486", Name = "RAMESH KUMAR", PNo = "44361W", Rank = "MCPO I", Unit = "INS DELHI", Type = "MASTER CHIEF PETTY OFFICER", Address = "Naval Base, Visakhapatnam", Dob = "12/05/1985", Mobile = "9812345678", RegRefund = 50, Balance = 2450.00m, Status = "Active" },
                    new Sailor { Id = "0001777487", Name = "SURESH SHARMA", PNo = "55210K", Rank = "CPO", Unit = "INS VIKRANT", Type = "CHIEF PETTY OFFICER", Address = "Eastern Naval Command, Vizag", Dob = "20/08/1988", Mobile = "9823456789", RegRefund = 50, Balance = 1200.00m, Status = "Active" },
                    new Sailor { Id = "0001777488", Name = "VIKRAM SINGH", PNo = "66123A", Rank = "PO", Unit = "INS KOLKATA", Type = "SENIOR SAILOR", Address = "Naval Quarters, Vizag", Dob = "15/01/1992", Mobile = "9834567890", RegRefund = 50, Balance = 850.00m, Status = "Active" },
                    new Sailor { Id = "0001777489", Name = "ANIL VERMA", PNo = "77890B", Rank = "LS", Unit = "INS MYSORE", Type = "JUNIOR SAILOR", Address = "Naval Dockyard, Vizag", Dob = "03/11/1995", Mobile = "9845678901", RegRefund = 50, Balance = 420.00m, Status = "Active" },
                    new Sailor { Id = "0001777490", Name = "RAJESH PATEL", PNo = "88901C", Rank = "SEA I", Unit = "INS SHIVALIK", Type = "JUNIOR SAILOR", Address = "ENC Barracks, Vizag", Dob = "28/02/1998", Mobile = "9856789012", RegRefund = 50, Balance = 0.00m, Status = "Deactive" }
                );
            }

            if (!Vendors.Any())
            {
                Vendors.AddRange(
                    new Vendor { Id = "V-001", Name = "INCS VISAKHAPATNAM", Contact = "Capt. S.K. Rao", Mobile = "9811000001", Address = "Naval Dockyard, Visakhapatnam", Gst = "37AAACI1234A1Z1" },
                    new Vendor { Id = "V-002", Name = "BEVERAGE DISTRIBUTORS", Contact = "Mr. R. K. Nair", Mobile = "9811000002", Address = "Industrial Estate, Vizag", Gst = "37AAACB5678B1Z5" },
                    new Vendor { Id = "V-003", Name = "IMPORT STORE", Contact = "Mr. A. Gupta", Mobile = "9811000003", Address = "Port Trust Area, Visakhapatnam", Gst = "37AAACI9012C1ZZ" },
                    new Vendor { Id = "V-004", Name = "CANTEEN STORE", Contact = "Cdr. P. Singh", Mobile = "9811000004", Address = "Naval Canteen, Kochi", Gst = "32AAACK3456D1ZA" },
                    new Vendor { Id = "V-005", Name = "KITCHEN DEPT", Contact = "CPO T. Verma", Mobile = "9811000005", Address = "INS Circars, Visakhapatnam", Gst = "37AAACK7890E1ZB" }
                );
            }

            if (!SystemSettings.Any())
            {
                SystemSettings.AddRange(
                    new SystemSetting { Key = "orgName", Value = "ARC AFLOAT RECREATION CENTER" },
                    new SystemSetting { Key = "orgShortName", Value = "ARC" },
                    new SystemSetting { Key = "orgAddress", Value = "Eastern Fleet, Eastern Naval Command" },
                    new SystemSetting { Key = "orgPhone", Value = "+91 8899001122" },
                    new SystemSetting { Key = "orgEmail", Value = "arc@navy.in" },
                    new SystemSetting { Key = "posName", Value = "POS-1" },
                    new SystemSetting { Key = "posIpAddress", Value = "192.168.1.105" },
                    new SystemSetting { Key = "receiptHeader", Value = "ARC AFLOAT RECREATION CENTER\nEASTERN NAVAL COMMAND" },
                    new SystemSetting { Key = "receiptFooter", Value = "Thank you! Visit again." }
                );
            }

            if (!Categories.Any())
            {
                var catLiquor = new CategoryMaster { Code = "CAT-01", Name = "LIQUOR", Description = "Alcoholic Beverages & Spirits" };
                var catFood = new CategoryMaster { Code = "CAT-02", Name = "FOOD", Description = "Cooked Meals, Snacks & Bread" };
                var catSoft = new CategoryMaster { Code = "CAT-03", Name = "SOFT DRINKS", Description = "Cold Drinks, Juices & Energy Drinks" };
                var catParty = new CategoryMaster { Code = "CAT-04", Name = "PARTY FOOD", Description = "Party Platters & Catering Items" };
                var catSnacks = new CategoryMaster { Code = "CAT-05", Name = "SNACKS", Description = "Packaged Chips & Finger Foods" };

                Categories.AddRange(catLiquor, catFood, catSoft, catParty, catSnacks);
                if (!Brands.Any())
            {
                Brands.AddRange(
                    new BrandMaster { Name = "ROYAL STAG", CategoryName = "LIQUOR", Description = "Seagram's Royal Stag Whisky" },
                    new BrandMaster { Name = "MCDOWELL NO 1", CategoryName = "LIQUOR", Description = "McDowell's No. 1 Whisky" },
                    new BrandMaster { Name = "OLD MONK", CategoryName = "LIQUOR", Description = "Old Monk Rum" },
                    new BrandMaster { Name = "CARLSBERG", CategoryName = "LIQUOR", Description = "Carlsberg Elephant Beer" },
                    new BrandMaster { Name = "KINGFISHER", CategoryName = "LIQUOR", Description = "Kingfisher Premium Beer" },
                    new BrandMaster { Name = "SMIRNOFF", CategoryName = "LIQUOR", Description = "Smirnoff Vodka" },
                    new BrandMaster { Name = "COCA COLA", CategoryName = "SOFT DRINKS", Description = "Coca Cola Carbonated Drink" },
                    new BrandMaster { Name = "PEPSI", CategoryName = "SOFT DRINKS", Description = "Pepsi Soft Drink" },
                    new BrandMaster { Name = "RED BULL", CategoryName = "SOFT DRINKS", Description = "Red Bull Energy Drink" }
                );
            }

            if (!ShipsUnits.Any())
            {
                ShipsUnits.AddRange(
                    new ShipUnitMaster { Name = "INS DELHI", Command = "Eastern Fleet", Status = "Active" },
                    new ShipUnitMaster { Name = "INS VIKRANT", Command = "Eastern Fleet", Status = "Active" },
                    new ShipUnitMaster { Name = "INS KOLKATA", Command = "Eastern Fleet", Status = "Active" },
                    new ShipUnitMaster { Name = "INS MYSORE", Command = "Eastern Fleet", Status = "Active" },
                    new ShipUnitMaster { Name = "INS SHIVALIK", Command = "Eastern Fleet", Status = "Active" },
                    new ShipUnitMaster { Name = "ENC BARRACKS", Command = "ENC Visakhapatnam", Status = "Active" },
                    new ShipUnitMaster { Name = "NAVAL DOCKYARD", Command = "ENC Visakhapatnam", Status = "Active" }
                );
            }

            if (!Ranks.Any())
            {
                Ranks.AddRange(
                    new RankMaster { Name = "MCPO I", Category = "MASTER CHIEF PETTY OFFICER" },
                    new RankMaster { Name = "MCPO II", Category = "MASTER CHIEF PETTY OFFICER" },
                    new RankMaster { Name = "CPO", Category = "CHIEF PETTY OFFICER" },
                    new RankMaster { Name = "PO", Category = "SENIOR SAILOR" },
                    new RankMaster { Name = "LS", Category = "JUNIOR SAILOR" },
                    new RankMaster { Name = "SEA I", Category = "JUNIOR SAILOR" },
                    new RankMaster { Name = "SEA II", Category = "JUNIOR SAILOR" }
                );
            }

            SaveChanges();

                SubCategories.AddRange(
                    new SubCategoryMaster { CategoryId = catLiquor.Id, CategoryName = "LIQUOR", Name = "WHISKY", Description = "Blended & Single Malt Whisky" },
                    new SubCategoryMaster { CategoryId = catLiquor.Id, CategoryName = "LIQUOR", Name = "BEER", Description = "Lager & Draught Beer" },
                    new SubCategoryMaster { CategoryId = catLiquor.Id, CategoryName = "LIQUOR", Name = "RUM", Description = "Dark & White Rum" },
                    new SubCategoryMaster { CategoryId = catLiquor.Id, CategoryName = "LIQUOR", Name = "VODKA", Description = "Flavored & Standard Vodka" },
                    new SubCategoryMaster { CategoryId = catLiquor.Id, CategoryName = "LIQUOR", Name = "WINE", Description = "Red & White Wine" },

                    new SubCategoryMaster { CategoryId = catFood.Id, CategoryName = "FOOD", Name = "BREAD/ROTI", Description = "Naan, Roti & Indian Breads" },
                    new SubCategoryMaster { CategoryId = catFood.Id, CategoryName = "FOOD", Name = "VEGETARIAN", Description = "Vegetarian Curries & Gravies" },
                    new SubCategoryMaster { CategoryId = catFood.Id, CategoryName = "FOOD", Name = "NON VEGETARIAN", Description = "Chicken, Mutton & Seafood" },
                    new SubCategoryMaster { CategoryId = catFood.Id, CategoryName = "FOOD", Name = "DESSERTS", Description = "Sweets & Ice Creams" },

                    new SubCategoryMaster { CategoryId = catSoft.Id, CategoryName = "SOFT DRINKS", Name = "COLD DRINK", Description = "Carbonated Soft Drinks" },
                    new SubCategoryMaster { CategoryId = catSoft.Id, CategoryName = "SOFT DRINKS", Name = "ENERGY DRINK", Description = "Energy & Health Drinks" },

                    new SubCategoryMaster { CategoryId = catParty.Id, CategoryName = "PARTY FOOD", Name = "PARTY VEG", Description = "Party Vegetarian Platters" },
                    new SubCategoryMaster { CategoryId = catParty.Id, CategoryName = "PARTY FOOD", Name = "PARTY NONVEG", Description = "Party Non-Veg Platters" }
                );
            }

            SaveChanges();
        }
    }
}
